function outputWindow   = IO_GUI()
% Generar ventana
screenSize  = get(0,'MonitorPositions');
outputWindow= findobj('Tag','eqSolutionGui');
pageicon    = imread(['utils',filesep,'help_ug.png'],...
    'BackgroundColor',[1,1,1]);
saveicon    = imread(['utils',filesep,'icono_guardar.png']);
openicon    = imread(['utils',filesep,'icono_abrir.png']);
if isempty(outputWindow) || ~ishandle(outputWindow) || ~isscalar(outputWindow)
    outputWindow = figure('Menu','none','Toolbar','figure',...
        'Color',[255,255,255]/255,'Name','Buffer Solution',...
        'WindowStyle','normal','NumberTitle','off','Resize','off',...
        'Units','pixels',...
        'Position',[screenSize(3:4)/2-[780,400]/2,780,400],...
        'Tag','eqSolutionGui');
    Panel2          = uipanel('Parent',outputWindow,...
        'Title','Equilibrium Solution',...
        'BackgroundColor',[255,255,255]/255);
    Tabla_Entrada   = uitable('Parent',Panel2,...
        'Units','normalized',...
        'Position',[0,1/4,30/100,3/4-1/8],...
        'RowName',{},...
        'ColumnName',{'COMPONENTE','VALOR','UNIDADES'},...
        'ColumnWidth',{  85 'auto' 'auto' },...
        'ColumnEditable',[ false true false ]);
    Tabla_Salida   = uitable('Parent',Panel2,...
        'Units','normalized',...
        'Position',[1-30/100,1/4,30/100,3/4-1/8],...
        'RowName',{},...
        'ColumnName',{'COMPONENTE','VALOR','UNIDADES'},...
        'ColumnWidth',{  80 'auto' 'auto' },...
        'ColumnEditable',[ false false false ]);
    texto1  = uicontrol('Parent',Panel2,...
        'Units','normalized',...
        'Style','text',...
        'String','INPUT',...
        'BackgroundColor','white',...
        'Position',[30/100/2-1/6/2,1-1/8+1/4/6,1/6,1/4/6]);
    texto2  = uicontrol('Parent',Panel2,...
        'Units','normalized',...
        'Style','text',...
        'String','OUTPUT',...
        'BackgroundColor','white',...
        'Position',[1-30/100+1/6/2,1-1/8+1/4/6,1/6,1/4/6]);
    Botones = uibuttongroup('Parent',Panel2,...
        'Units','normalized',...
        'Title','RAICES',...
        'BackgroundColor','white',...
        'Position',[1-30/100,1/4/10,30/100,9/4/10]);
    Boton_1 = uicontrol('Parent',Botones,...
        'Units','normalized',...
        'Style','radiobutton',...
        'String','pH=',...
        'BackgroundColor','white',...
        'Position',[1/22,1/11,1-1/22,3/11],...
        'Enable','off');
    Boton_2 = uicontrol('Parent',Botones,...
        'Units','normalized',...
        'Style','radiobutton',...
        'String','pH=',...
        'BackgroundColor','white',...
        'Position',[1/22,4/11,1-1/22,3/11],...
        'Enable','off');
    Boton_3 = uicontrol('Parent',Botones,...
        'Units','normalized',...
        'Style','radiobutton',...
        'String','pH=',...
        'BackgroundColor','white',...
        'Position',[1/22,7/11,1-1/22,3/11],...
        'Enable','off');
    DatosIniciales      =    ...
        {...        
        '1'             0.4         'W%';...
        '2'             0.3         'W%';...        
        '3'             0.3         'W%';...        
        };
    DatosDeRespuesta      =    ...
        {...                
        'pH'            []      '';...
        'pOH'           []      '';...        
        };
    BotonCalcular = uicontrol('Parent',Panel2,...
        'Units','normalized',...
        'Style','pushbutton',...
        'String','CALCULAR',...
        'Position',[30/100/2-1/6/2,1/4/2-1/4/3/2,1/6,1/4/3]);
    Herramientas    = findall(outputWindow,'Type','uitoolbar');
    BotonesEnBarra  = ...
        [...
        get(findall(outputWindow,'Type','uipushtool'),'ToolTipString');...
        get(findall(outputWindow,'Type','uitoggletool'),'ToolTipString');
        ];
    for i=1:size(BotonesEnBarra,1)
        if ...
                ~strcmp(BotonesEnBarra{i},'Insert Legend') && ...
                ~strcmp(BotonesEnBarra{i},'Data Cursor') && ...
                ~strcmp(BotonesEnBarra{i},'Pan') && ...
                ~strcmp(BotonesEnBarra{i},'Zoom Out') && ...
                ~strcmp(BotonesEnBarra{i},'Zoom In')
            set(findall(Herramientas,'ToolTipString',...
                BotonesEnBarra{i}),'Visible','Off');
        end
    end    
    BotonDeGuardar  = uipushtool(Herramientas,...
        'CData',            saveicon,...        
        'Tag',              'uipushtool2',...
        'TooltipString',    'Guardar CSV',...
        'Separator',        'on');
    BotonDeAbrir    = uipushtool(Herramientas,...
        'CData',            openicon,...        
        'Tag',              'uipushtool3',...
        'TooltipString',    'Abrir CSV');
    BotonDeReporte  = uipushtool(Herramientas,...
        'CData',            pageicon,...        
        'Tag',              'uipushtool1',...
        'TooltipString',    'Ver procedimiento de solución',...
        'Separator',        'on');
    Eje1            = axes('Parent',Panel2,...
        'Units','normalized',...
        'OuterPosition',...
        [30/100,0,40/100,1/2],...
        'Box','on','Layer','bottom',...
        'XTick',[],'YTick',[]);
    Eje2            = axes('Parent',Panel2,...
        'Units','normalized',...
        'OuterPosition',...
        [30/100,1/2,40/100,1/2],...
        'Box','on','Layer','bottom',...
        'XTick',[],'YTick',[]);
    handles = struct('Tabla_Entrada',Tabla_Entrada,...
        'Tabla_Salida',Tabla_Salida,'texto1',texto1,...
        'texto2',texto2,'Panel2',Panel2,...
        'Ventana',outputWindow,'Botones',Botones,...
        'Boton_1',Boton_1,'Boton_2',Boton_2,...
        'Boton_3',Boton_3,'BotonDeReporte',BotonDeReporte,...
        'Herramientas',Herramientas,...
        'BotonDeGuardar',BotonDeGuardar,...
        'BotonDeAbrir',BotonDeAbrir,...
        'Eje1',Eje1,'Eje2',Eje2);
    handles.BotonCalcular = BotonCalcular;
    set(Tabla_Entrada,'Data',DatosIniciales);
    set(Tabla_Salida,'Data',DatosDeRespuesta);
    set(BotonCalcular,...
        'Callback',{@funcionDeCalcular,handles});
    set(Tabla_Entrada,...
        'CellEditCallback',{@funcionDeCalcular,handles});
    set(Botones,...
        'SelectedObject',[],'SelectionChangeFcn',...
        {@CambioDeBoton,handles});
    set(BotonDeReporte,'ClickedCallback',...
        {@MostrarProcedimiento,handles});
    set(BotonDeGuardar,'ClickedCallback',...
        {@GenerarCSV,handles});
    set(BotonDeAbrir,'ClickedCallback',...
        {@AbrirCSV,handles});
else
    figure(outputWindow);
end
end

function funcionDeCalcular(~,~,~,varargin)
end
