function getRkQk
[~,a_mk_chars]  = cargarCSV('a_mk.csv');
[~,RkQk_chars]  = cargarCSV('RkQk.csv');
a_mk            = cellfun(@str2num,a_mk_chars);
RkQk            = RkQk_chars;
expected1stLine = {...
    'MAIN GROUP';...
    'MAIN GROUP NAME';...
    'k';...
    'Group  Symbol';...
    'Rk';...
    'Qk';...
    'Example';...
    };
for i=1:length(expected1stLine)
    [~,col]     = find(strcmp(expected1stLine{i},RkQk_chars));
    if ~isnan(str2double(RkQk(2,col)))
        RkQk(2:end,col) =...
            num2cell(cellfun(@str2num,RkQk_chars(2:end,col)));
    end
end
end