function subgroup_parameters = getSubGroupParameters()
%SUBGROUP PARAMETERS returns parameters of all UNIFAC subgroups
[~,subgroup_parameters_chars]  ...
                = cargarCSV('subgroup_parameters.csv');
subgroup_parameters ...
                = subgroup_parameters_chars;
parameterNames = {...
    'MAIN GROUP';...
    'MAIN GROUP NAME';...
    'k';...
    'Group  Symbol';...
    'Rk';...
    'Qk';...
    'Example';...
    };
for i=1:length(parameterNames)
    [~,col]     = ...
        find(strcmp(parameterNames{i},...
        subgroup_parameters_chars));
    if ~isnan(str2double(subgroup_parameters(2,col)))
        subgroup_parameters(2:end,col) =...
            num2cell(cellfun(@str2num,...
            subgroup_parameters_chars(2:end,col)));
    end
end
end